### ISSUE TITLE
v1.1 Golive checklist

### ISSUE THREAD

**Issue by doerfli** [etherisc/staking-ui#436]
- [x] smart contract deployment
- [x] redis setup
- [x] background processor deployment
- [x] monitoring of background processor
- [x] configure wallet and verify contract address for `mainnet-staking-processor`
- [x] webapp deployment v1.1.1
- [x] enable gasless staking feature
- [x] enable restaking feature
